import React,{useEffect,useState} from 'react'
import {adminLogin,adminLogout,adminRegister,adminSession,api,applyTheme,settings} from './api'
import Navigation from './components/Navigation'
import Icon from './components/Icon'
import BrandLogo from './components/BrandLogo'
import MetricCard from './components/MetricCard'

const fmtBytes=(v)=>{const n=Number(v||0);if(n<1024)return `${n} B`;if(n<1024**2)return `${(n/1024).toFixed(1)} KiB`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} MiB`;return `${(n/1024**3).toFixed(2)} GiB`}
const fmtTime=(v)=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'—'

function LoginPage({onLoggedIn}){
  const [cap,setCap]=useState(null),[health,setHealth]=useState(null),[mode,setMode]=useState('login'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[email,setEmail]=useState(''),[displayName,setDisplayName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{Promise.allSettled([api('/api/v1/auth/capabilities'),api('/health')]).then(([c,h])=>{if(c.status==='fulfilled'){setCap(c.value);if(c.value.setup_required)setMode('register')}if(h.status==='fulfilled')setHealth(h.value)}).catch(e=>setError(e.message||String(e)))},[])
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(mode==='register'){if(!cap?.setup_required)throw new Error('管理员后台只允许首次初始化管理员；普通用户请从 3005 注册');if(password!==confirm)throw new Error('两次密码不一致');await adminRegister({username,password,email,displayName})}else await adminLogin(username,password);const me=await api('/api/v1/auth/me');if(me.role!=='admin')throw new Error('该账户不是管理员');onLoggedIn()}catch(e){setError(e.message||String(e))}finally{setBusy(false)}}
  const cards=[
    ['users','账户管理',cap?.setup_required?'待初始化':'已启用','用户、角色与账户状态'],
    ['key','认证隔离','Session + Key','Web 与 Zotero 凭据分离'],
    ['history','缓存复用','DOI 版本锁定','跨设备复用当前译文'],
    ['tasks','Cloud 状态',health?.ok?'在线':'检查中',health?.version?`Cloud ${health.version}`:'正在读取服务状态'],
  ]
  return <main className="admin-login-shell"><section className="admin-login-stage"><div className="admin-login-intro"><div className="login-brand-row"><BrandLogo/><div><p className="eyebrow">ADMIN · 3006</p><h1>Zotero-full-translate</h1></div></div><p className="admin-login-copy">管理端只负责用户、账户状态和全局运营统计。普通用户的翻译 API 地址、模型和密钥始终在 3005 用户中心独立维护。</p><div className="login-stat-grid">{cards.map(([icon,label,value,detail])=><article className="login-stat" key={label}><span className="login-stat-icon"><Icon name={icon} size={22}/></span><div><small>{label}</small><strong>{value}</strong><span>{detail}</span></div></article>)}</div></div><section className="admin-login-card"><div className="login-form-title"><span className="login-form-icon"><Icon name={cap?.setup_required?'users':'key'} size={24}/></span><div><p className="eyebrow">管理员认证</p><h2>{cap?.setup_required?'初始化管理员':'登录管理后台'}</h2></div></div><p className="support">{cap?.setup_required?'全新服务器的第一个账户在这里创建并自动成为管理员。':'管理员会话通过 HttpOnly Cookie 保存，不与 Zotero API Key 混用。'}</p><form onSubmit={submit} className="login-form">{mode==='register'&&<><label>显示名称<input value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label><label>邮箱<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label></>}<label>用户名<input value={username} onChange={e=>setUsername(e.target.value)} autoFocus autoComplete="username"/></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='register'?'new-password':'current-password'}/></label>{mode==='register'&&<label>确认密码<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/></label>}{error&&<div className="global-error compact"><Icon name="warning" size={20}/><span>{error}</span></div>}<button className="md-button filled login-submit" disabled={busy||!username||password.length<8}><Icon name={mode==='register'?'users':'key'} size={18}/>{busy?'处理中…':mode==='register'?'创建首任管理员':'登录后台'}</button></form><div className="login-security-note"><Icon name="info" size={18}/><span>3006 不提供普通用户 Provider 密钥配置。</span></div></section></section></main>
}

function Overview({summary,status}){return <div className="page-stack"><section className="overview-hero"><div><span className="eyebrow">Cloud {status?.version||'2.3'}</span><h2>运营与用户统计</h2><p>Provider API 地址与密钥属于每个普通用户，管理后台不统一配置用户翻译服务。</p></div><div className="hero-state"><span>服务状态</span><strong>{status?.ok?'正常':'异常'}</strong><small>队列 {status?.queue_depth||0}</small></div></section><section className="metric-grid admin-metric-grid"><MetricCard icon="users" label="用户总数" value={summary?.total_users||0} tone="primary"/><MetricCard icon="users" label="今日新增用户" value={summary?.new_users_today||0} tone="secondary"/><MetricCard icon="services" label="今日调用次数" value={summary?.today_calls||0}/><MetricCard icon="download" label="今日调用字节" value={fmtBytes(summary?.today_bytes)}/></section><section className="metric-grid"><MetricCard icon="users" label="今日活跃用户" value={summary?.active_users_today||0}/><MetricCard icon="services" label="24h 活跃设备" value={summary?.active_devices_24h||0}/><MetricCard icon="key" label="有效 Zotero API Key" value={summary?.active_api_keys||0}/><MetricCard icon="history" label="今日缓存复用" value={summary?.today_cache_hits||0} tone="success"/><MetricCard icon="tasks" label="今日任务" value={summary?.today_jobs||0} supporting={`${summary?.today_completed||0} 完成 · ${summary?.today_failed||0} 失败`}/></section><section className="metric-grid"><MetricCard icon="check" label="累计完成任务" value={summary?.all_completed_jobs||0} tone="success"/><MetricCard icon="history" label="累计共享复用" value={summary?.shared_cache_reuse_total||0}/><MetricCard icon="tasks" label="运行中" value={status?.active_jobs||0}/><MetricCard icon="tasks" label="排队中" value={status?.queued_jobs||0}/></section></div>}

function Users({users,onRefresh}){const [selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[error,setError]=useState('');async function open(row){setSelected(row.user.id);try{setDetail(await api(`/api/v1/admin/users/${row.user.id}`))}catch(e){setError(e.message||String(e))}}async function toggle(row){try{await api(`/api/v1/admin/users/${row.user.id}`,{method:'PATCH',body:JSON.stringify({is_active:!row.user.is_active})});await onRefresh()}catch(e){setError(e.message||String(e))}}async function resetPassword(){const p=window.prompt('输入新密码（至少 8 位）');if(!p)return;try{await api(`/api/v1/admin/users/${selected}`,{method:'PATCH',body:JSON.stringify({password:p})});alert('密码已重置，用户旧会话已撤销')}catch(e){setError(e.message||String(e))}}return <div className="page-stack"><section className="md-card"><div className="section-heading"><div><span className="overline">账户</span><h3>用户管理</h3></div><span>{users.length} 个账户</span></div>{error&&<div className="global-error">{error}</div>}<div className="admin-user-table"><div className="admin-user-row admin-user-head"><b>用户</b><b>今日调用</b><b>今日字节</b><b>设备</b><b>API Key</b><b>状态</b><b/></div>{users.map(row=><div className="admin-user-row" key={row.user.id}><button className="user-name-button" onClick={()=>open(row)}><strong>{row.user.display_name||row.user.username}</strong><small>{row.user.username} · {row.user.role}</small></button><span>{row.today_calls}</span><span>{fmtBytes(row.today_bytes)}</span><span>{row.device_count}</span><span>{row.api_key_count||0}</span><span>{row.user.is_active?'正常':'停用'}</span><button className="md-button text" onClick={()=>toggle(row)}>{row.user.is_active?'停用':'启用'}</button></div>)}</div></section>{detail&&<section className="md-card"><div className="section-heading"><div><span className="overline">用户详情</span><h3>{detail.user.display_name||detail.user.username}</h3></div><button className="icon-button" onClick={()=>{setDetail(null);setSelected(null)}}><Icon name="close"/></button></div><section className="metric-grid"><MetricCard icon="services" label="今日调用" value={detail.today.calls}/><MetricCard icon="download" label="今日字节" value={fmtBytes(detail.today.total_bytes)}/><MetricCard icon="history" label="累计缓存命中" value={detail.total_cache_hits}/><MetricCard icon="services" label="客户端实例" value={detail.device_count}/><MetricCard icon="key" label="有效 API Key" value={detail.api_key_count||0}/></section><div className="detail-device-list">{detail.devices.map(d=><div key={d.id}><Icon name="services"/><div><strong>{d.name}</strong><small>{d.platform||'未知'} · {fmtTime(d.last_seen_at)}</small></div></div>)}</div><button className="md-button tonal" onClick={resetPassword}>重置用户密码</button></section>}</div>}

function Settings({onLogout}){return <div className="page-stack"><section className="md-card"><div className="section-heading"><div><span className="overline">后台职责</span><h3>管理端口 3006</h3></div></div><p>该端口只负责用户管理、账户状态和全局运营统计。翻译 Provider 的 API 地址、模型和密钥全部由用户在 3005 端口自行维护。</p><button className="md-button text" onClick={onLogout}>退出管理员账户</button></section></div>}

export default function App(){const [loggedIn,setLoggedIn]=useState(false),[view,setView]=useState('overview'),[summary,setSummary]=useState(null),[status,setStatus]=useState(null),[users,setUsers]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);async function refresh(){try{const [a,s,u,me]=await Promise.all([api('/api/v1/admin/summary'),api('/api/v1/system/status'),api('/api/v1/admin/users'),adminSession()]);if(me.role!=='admin')throw new Error('administrator access required');setSummary(a);setStatus(s);setUsers(u);setError('');setLoggedIn(true)}catch(e){setError(e.message||String(e));setLoggedIn(false)}finally{setLoading(false)}}useEffect(()=>{applyTheme(settings.theme);refresh()},[]);useEffect(()=>{if(!loggedIn)return;const t=setInterval(refresh,10000);return()=>clearInterval(t)},[loggedIn]);async function doLogout(){await adminLogout();setLoggedIn(false)}if(!loggedIn&&!loading)return <LoginPage onLoggedIn={()=>{setLoggedIn(true);setLoading(true);refresh()}}/>;if(loading)return <div className="loading-screen">加载管理后台…</div>;return <div className="md-app-shell"><Navigation view={view} onChange={setView}/><div className="md-main-area"><header className="md-top-app-bar"><div className="top-title"><h1>{view==='overview'?'统计总览':view==='users'?'用户管理':'后台设置'}</h1></div><div className="top-actions"><span className={`connection-state ${status?.ok?'online':'offline'}`}><span/>{status?.ok?'已连接':'异常'}</span><button className="icon-button" onClick={refresh}><Icon name="refresh"/></button><button className="md-button text" onClick={doLogout}>退出</button></div></header><main className="md-content">{error&&loggedIn&&<div className="global-error"><Icon name="warning"/><span>{error}</span></div>}{view==='overview'?<Overview summary={summary} status={status}/>:view==='users'?<Users users={users} onRefresh={refresh}/>:<Settings onLogout={doLogout}/>}</main></div></div>}
